ControlPostgres/Controllers/RegistroController.cs
using ControlPostgres.Contexto.Entities;
using ControlPostgres.RepositorioClases;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ControlPostgres.Controllers
{
    enum Departamento
    {
        Monitoreo = 1
    }

    enum CargoDepaPM
    {

        DirectorPM = 2,
        JefeInmediatoMonitoreo = 3,
        MonitordeCamaras = 5,
        EncargadoTurno = 6

    }
    public class RegistroController : Controller
    {

        BD_ControlVacacionesContext bd = new BD_ControlVacacionesContext();
        Repositorio puente = new Repositorio();
        public static TbEmpleado empleado = new TbEmpleado();

        public ActionResult RegistrarEmp()
        {
            ViewData["Depto"] = new SelectList(bd.TbDepartamentos, "DeptoId", "DeptoNombre");
            ViewData["Cargos"] = new SelectList(bd.TbCargos, "CargoId", "CargoNombre");
            ViewData["Vacaciones"] = new SelectList(bd.TbVacaciones, "VacacionesId", "VacacionesEstado");



            return View();
        }

        [HttpPost]
        public ActionResult RegistrarEmp(TbEmpleado model)
        {
            ViewData["Depto"] = new SelectList(bd.TbDepartamentos, "DeptoId", "DeptoNombre");
            ViewData["Cargos"] = new SelectList(bd.TbCargos, "CargoId", "CargoNombre");
            ViewData["Vacaciones"] = new SelectList(bd.TbVacaciones, "VacacionesId", "VacacionesEstado");

            Boolean logico;
            try
            {


                if (ModelState.IsValid)
                {
                    logico = puente.Registrar(model);

                    switch (logico)
                    {
                        case true:
                            ModelState.Clear();
                            return View("Login");
                        case false:
                            ViewBag.Registro = "No registro";
                            return View("RegistrarEmp");


                    }
                }
                else
                {
                    return View("RegistrarEmp");
                }
            }
            catch (Exception)
            {

                throw;
            }
        }

        public ActionResult Login()
        {
            ViewBag.Opcion = TempData["CambioContra"];
            return View();
        }
        [HttpPost]
        public IActionResult Login(TbEmpleado usuario)
        {
            ViewBag.Opcion = "";
            TempData["Logueo"] = "";
            TbEmpleado user = new TbEmpleado();

            try
            {


                if (!string.IsNullOrEmpty(usuario.EmpleadoCodigo) && !string.IsNullOrEmpty(usuario.EmpleadoContraseña))
                {
                    user = bd.TbEmpleados.FirstOrDefault(u => u.EmpleadoCodigo == usuario.EmpleadoCodigo && u.EmpleadoContraseña == usuario.EmpleadoContraseña);
                    if (user != null)
                    {
                        if (user.DeptoId == (int)Departamento.Monitoreo && user.CargoId == (int)CargoDepaPM.MonitordeCamaras || user.DeptoId == (int)Departamento.Monitoreo && user.CargoId == (int)CargoDepaPM.EncargadoTurno)
                        {
                            var claims = new List<Claim>
                            {
                                new Claim(ClaimTypes.Name,user.EmpleadoCodigo)
                            };
                            var identity = new ClaimsIdentity(
                                claims, CookieAuthenticationDefaults.AuthenticationScheme);
                            var principal = new ClaimsPrincipal(identity);
                            var props = new AuthenticationProperties();
                            HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal, props).Wait();
                            HttpContext.Session.SetString("SessionUser", JsonConvert.SerializeObject(user));
                            TempData["Logueo"] = "Logueo Exitoso";
                            return RedirectToAction("PerfilColaborador", "Perfil");

                        }
                        else if (user.DeptoId == (int)Departamento.Monitoreo && user.CargoId == (int)CargoDepaPM.DirectorPM)
                        {
                            var claims = new List<Claim>
                            {
                            new Claim(ClaimTypes.Name,user.EmpleadoCodigo)
                            };
                            var identity = new ClaimsIdentity(
                                claims, CookieAuthenticationDefaults.AuthenticationScheme);
                            var principal = new ClaimsPrincipal(identity);
                            var props = new AuthenticationProperties();
                            HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal, props).Wait();
                            HttpContext.Session.SetString("SessionUser", JsonConvert.SerializeObject(user));
                            TempData["Logueo"] = "Logueo Exitoso";
                            return RedirectToAction("PerfilDirector", "Perfil");
                        }
                        else if (user.DeptoId == (int)Departamento.Monitoreo && user.CargoId == (int)CargoDepaPM.JefeInmediatoMonitoreo)
                        {
                            var claims = new List<Claim>
                            {
                    new Claim(ClaimTypes.Name,user.EmpleadoCodigo)
                            };
                            var identity = new ClaimsIdentity(
                                claims, CookieAuthenticationDefaults.AuthenticationScheme);
                            var principal = new ClaimsPrincipal(identity);
                            var props = new AuthenticationProperties();
                            HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal, props).Wait();
                            HttpContext.Session.SetString("SessionUser", JsonConvert.SerializeObject(user));
                            TempData["Logueo"] = "Logueo Exitoso";
                            return RedirectToAction("PerfilJefe", "Perfil");
                        }

                    }


                }
                else
                {
                    ViewBag.Opcion = "Campos Vacios";
                    return View("Login");
                }
                ViewBag.Opcion = "Usuario Incorrecto";
                return View("Login");
            }
            catch (Exception)
            {

                throw;
            }
        }

        public IActionResult RecuperarContra()
        {
            return View();
        }
        [HttpPost]
        public IActionResult RecuperarContra(TbContraseña contra)
        {
            if (!string.IsNullOrEmpty(contra.codigoempleado) && !string.IsNullOrEmpty(contra.fechanacimiento.ToString()) && !string.IsNullOrEmpty(contra.telefono))
            {
                TbEmpleado user = new TbEmpleado();

                user = bd.TbEmpleados.FirstOrDefault(u => u.EmpleadoCodigo == contra.codigoempleado && u.FechaNacimiento == contra.fechanacimiento && u.EmpleadoTelefono == contra.telefono);
                if (user != null)
                {

                    HttpContext.Session.SetString("SessionContra", JsonConvert.SerializeObject(user));
                    TempData["DatosCorrectos"] = "datos correctos";
                    return RedirectToAction("ConfirmaContraseña");
                }
                else
                {
                    ViewBag.Opcion = "Credenciales no coinciden";
                    return View();
                }
            }
            else
            {
                ViewBag.Opcion = "Campos vacios";
                return View();
            }

        }

        public IActionResult Logout()
        {
            HttpContext.Session.Remove("SessionUser");
            TempData["Salir"] = "Salio";
            return RedirectToAction("Index", "Home");
        }
        private bool TbEmpleadoExists(int id)
        {
            return bd.TbEmpleados.Any(e => e.EmpleadoId == id);
        }

        public IActionResult ConfirmaContraseña()
        {
            ViewBag.Opcion = TempData["DatosCorrectos"];
            
            return View();
        }
        [HttpPost]
        public IActionResult ConfirmaContraseña(TbReContra recontra)
        {
            TbEmpleado empleado = JsonConvert.DeserializeObject<TbEmpleado>(HttpContext.Session.GetString("SessionContra"));
            if(!string.IsNullOrEmpty(recontra.Contra) && !string.IsNullOrEmpty(recontra.RepetirContra)) { 
            if (recontra.Contra == recontra.RepetirContra)
            {
                if (ModelState.IsValid)
                {

                    var usuario = bd.TbEmpleados.Where(u => u.EmpleadoId == empleado.EmpleadoId).FirstOrDefault();
                    usuario.EmpleadoContraseña = recontra.RepetirContra;
                    bd.SaveChanges();
                    HttpContext.Session.Remove("SessionContra");
                        TempData["CambioContra"] = "cambio correcto";
                    return RedirectToAction("Login");

                }
                else
                {
                    ViewBag.Problemacontra = "Lo sentimos ha ocurrido un problema, por favor hable con el administrador del portal";
                    return View();
                }
            }
            else 
            {
                   
                    ViewBag.Opcion = "no iguales";
                    return View();
                }
            }

ControlPostgres/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ControlPostgres</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        @if (@HttpContextAccessor.HttpContext.Session.GetString("SessionUser") != null)
        {<nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3" id="NavLogin">
                <div class="container">
                    <a class="navbar-brand" id="muni">Municipalidad de Villa Nueva</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">

                            <li class="nav-item">
                                <a class="nav-link" id="navbarinicio" asp-area="" asp-controller="Perfil" asp-action="DetailsPerfil">Perfil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="navbarinicio" asp-area="" asp-controller="Registro" asp-action="Logout">Salir</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>}
        else
        {
<nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3" id="NavRegistro">
    <div class="container">
        <a class="navbar-brand" id="muni">Municipalidad de Villa Nueva</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">

                <li class="nav-item">
                    <a class="nav-link" id="navbarinicio" asp-area="" asp-controller="Registro" asp-action="RegistrarEmp">Registrarme</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="navbarinicio" asp-area="" asp-controller="Registro" asp-action="Login">Ingresar</a>
                </li>

            </ul>
        </div>
    </div>
</nav>}
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" id="pie">
        <div class="container">
            &copy; 2021 - Ricardo Adolfo Argueta Escobar - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <link href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet" />
    <script src="https://cdn.rawgit.com/dubrox/Multiple-Dates-Picker-for-jQuery-UI/master/jquery-ui.multidatespicker.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>